<a href="https://colab.research.google.com/github/irfan-karimi/AI/blob/main/Task1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import numpy as numpy

array_1d = numpy.arange(10)
print(array_1d)




array_2d = numpy.arange(1, 10).reshape(3, 3)
print(array_2d)

array_3d = numpy.random.randint(1, 101, size=(2, 3, 4))
print(array_3d)

[0 1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[[92 36  4 31]
  [66 69 29 48]
  [96 23 99 14]]

 [[12 26 52 15]
  [ 6 79 13 33]
  [ 6 46 35 99]]]
