<a href="https://colab.research.google.com/github/irfan-karimi/AI/blob/main/Task1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import numpy as np

# Example arr2
arr2 = np.array([[1, 2, 3],
                 [4, 5, 6],
                 [7, 8, 9]])

# Extracting the second row (index 1)
second_row = arr2[1]
print(second_row)

import numpy as np

array_2d = np.arange(1, 10).reshape(3, 3)
print(array_2d)




[4 5 6]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [5]:
import numpy as np

array_3d = np.random.randint(1, 101, size=(2, 3, 4))
print(array_3d)

[[[16 15 91 66]
  [42 88  1 98]
  [72 83 84 24]]

 [[11 85 73 86]
  [68 31 18 91]
  [47 70 53  3]]]


In [4]:
import numpy as np

# Example arr1 (1D array with 10 elements)
arr1 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Reshaping the 1D array into a 2x5 2D array
reshaped_arr = arr1.reshape(2, 5)
print(reshaped_arr)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [3]:
# Adding 10 to each element of arr1
arr1_plus_10 = arr1 + 10
print(arr1_plus_10)


NameError: name 'arr1' is not defined

In [2]:
# Example arr2 (2D array)
arr2 = np.array([[1, 2, 3],
                 [4, 5, 6],
                 [7, 8, 9]])

# Multiplying each element of arr2 by 2
arr2_times_2 = arr2 * 2
print(arr2_times_2)


[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


In [7]:
import numpy as numpy

array_1d = numpy.arange(10)
print(array_1d)




array_2d = numpy.arange(1, 10).reshape(3, 3)
print(array_2d)

[0 1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
